<a href="https://colab.research.google.com/github/WlonWUsk/AryaDevRijal-Concepts-of-AI-and-Machine-Learning/blob/main/2548859_AryaDev_ws1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

WORKSHOP 1
TASK 1


1)


In [1]:
import numpy as np
arr1 = np.zeros((2, 2))
print(arr1)

[[0. 0.]
 [0. 0.]]


2)

In [2]:
import numpy as np
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3)


In [3]:
arr3 = np.full((3, 3), 7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4)

In [4]:
arr4 = np.zeros_like(arr2)
print(arr4)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


5)

In [5]:
arr5 = np.ones_like(arr2)
print(arr5)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


6)

In [6]:
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print(arr6)

[1 2 3 4]


TASK 2


1)

In [9]:
import numpy as np

arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2)


In [10]:
arr2 = np.arange(0,9).reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3)


In [14]:
arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4)


In [13]:
arr4 = np.random.random(30)
mean_value = arr4.mean()
print(arr4)
print("Mean:", mean_value)

[0.91090932 0.74275608 0.81288376 0.41346211 0.30537911 0.94195523
 0.87995263 0.99001639 0.60225604 0.80388645 0.79405228 0.56442817
 0.71691998 0.35866842 0.29633459 0.59848826 0.62549676 0.24658894
 0.07828061 0.07280874 0.60474597 0.15274821 0.36083814 0.71962751
 0.83158696 0.33571293 0.83689379 0.5412588  0.28415359 0.9316448 ]
Mean: 0.5784911520407944


5)


In [12]:
arr5 = np.random.random((10, 10))
min_val = arr5.min()
max_val = arr5.max()
print("Min:", min_val)
print("Max:", max_val)

Min: 0.01186252007179256
Max: 0.999486979079951


6)

In [11]:
arr6 = np.zeros(10)
arr6[4] = 1
print(arr6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7

In [23]:
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


8

In [24]:
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print(arr8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9)

In [25]:
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print(arr9)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


TASK 3

1

In [17]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])
add_xy = x + y
print(add_xy)

[[ 6  8]
 [10 13]]


2

In [18]:
sub_xy = x - y
print(sub_xy)

[[-4 -4]
 [-4 -3]]


3

In [20]:
mul_x = x * 3
print(mul_x)

[[ 3  6]
 [ 9 15]]


4

In [21]:
square_x = x ** 2
print(square_x)

[[ 1  4]
 [ 9 25]]


5

In [22]:
dot_vw = np.dot(v, w)
print(dot_vw)

219


6

In [26]:
concatenate_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concatenate_xy_row)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


7)

In [28]:
try:
    concat_x_v = np.concatenate((x, v), axis=0)
except Exception as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


8

In [30]:

v_reshaped = v.reshape(1,2)
concat_x_v_fixed = np.concatenate((x, v_reshaped), axis=0)
print(concat_x_v_fixed)


[[ 1  2]
 [ 3  5]
 [ 9 10]]


1)

In [31]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

2)

In [32]:
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)

print("A · A_inv =\n", identity)

A · A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


3)

In [33]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal? ", np.array_equal(AB, BA))

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Are AB and BA equal?  False


4)

In [34]:
AB_T = (np.dot(A, B)).T
B_TA_T = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T · A^T =\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))

(AB)^T =
 [[23 51]
 [13 29]]
B^T · A^T =
 [[23 51]
 [13 29]]
Are they equal? True


5)


In [35]:
# Coefficient matrix A
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

# Constant matrix B
B_eq = np.array([-1, -3, 9])

6)

In [36]:
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("Solution [x, y, z] =", X)


Solution [x, y, z] = [ 2.  1. -2.]


7)

In [37]:
A_inv = np.linalg.inv(A_eq)
X = np.dot(A_inv, B_eq)
print("Solution [x, y, z] =", X)

Solution [x, y, z] = [ 2.  1. -2.]


Excercise 4.2

In [38]:
import numpy as np
import time
#here we are declaring the size of the arrays
N = 1_000_000

# Python lists
list1 = list(range(N))
list2 = list(range(N))

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)
start_time = time.time()

# Using list comprehension for element-wise addition
list_sum = [list1[i] + list2[i] for i in range(N)]

end_time = time.time()
print("Time taken for Python lists addition: {:.5f} seconds".format(end_time - start_time))
start_time = time.time()

# Using NumPy's vectorized addition
array_sum = arr1 + arr2

#displaying the result of the difference of the time between element wise and numpy additions
end_time = time.time()
print("Time taken for NumPy arrays addition: {:.5f} seconds".format(end_time - start_time))


Time taken for Python lists addition: 0.11224 seconds
Time taken for NumPy arrays addition: 0.00517 seconds


Element time wise multiplication

In [39]:
#Now we will try with multiplications
import numpy as np
import time

#declaring the size fo arrays
N = 1_000_000

# Python lists
list1 = list(range(1, N+1))
list2 = list(range(1, N+1))

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)
start_time = time.time()

# Using list comprehension for multiplication
list_mul = [list1[i] * list2[i] for i in range(N)]

end_time = time.time()
print("Time taken for Python lists multiplication: {:.5f} seconds".format(end_time - start_time))
start_time = time.time()

# Using NumPy vectorized multiplication
array_mul = arr1 * arr2

#displaying the result of the difference of the time between element wise and numpy multiplications
end_time = time.time()
print("Time taken for NumPy arrays multiplication: {:.5f} seconds".format(end_time - start_time))

Time taken for Python lists multiplication: 0.13129 seconds
Time taken for NumPy arrays multiplication: 0.00283 seconds


Dot product

In [40]:
import numpy as np
import time
#declaring arryas of huge size
N = 1_000_000

# Python lists
list1 = list(range(1, N+50))
list2 = list(range(1, N+50))

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)
start_time = time.time()

# Compute dot product manually
dot_list = sum(list1[i] * list2[i] for i in range(N))

end_time = time.time()
print("Time taken for Python lists dot product: {:.5f} seconds".format(end_time - start_time))
start_time = time.time()

# Using NumPy's dot function
dot_array = np.dot(arr1, arr2)

#displaying the result of the difference of the time between the python list dot product and numpy dot product
end_time = time.time()
print("Time taken for NumPy arrays dot product: {:.5f} seconds".format(end_time - start_time))

Time taken for Python lists dot product: 0.10481 seconds
Time taken for NumPy arrays dot product: 0.00252 seconds


Matrix Multiplication

In [ ]:
import numpy as np
import time
import random
N = 1000

# Generate 1000x1000 matrices with random integers 0-10
matrix1 = [[random.randint(0, 10) for _ in range(N)] for _ in range(N)]
matrix2 = [[random.randint(0, 10) for _ in range(N)] for _ in range(N)]
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)
start_time = time.time()

# Initialize result matrix with zeros
result_list = [[0 for _ in range(N)] for _ in range(N)]

# Perform multiplication
for i in range(N):
    for j in range(N):
        for k in range(N):
            result_list[i][j] += matrix1[i][k] * matrix2[k][j]

end_time = time.time()
print("Time taken for Python lists matrix multiplication: {:.5f} seconds".format(end_time - start_time))
start_time = time.time()

result_np = np.dot(np_matrix1, np_matrix2)  # or np_matrix1 @ np_matrix2

end_time = time.time()
print("Time taken for NumPy arrays matrix multiplication: {:.5f} seconds".format(end_time - start_time))